### ISSUE TITLE
AUR package : go compilation issue

### ISSUE THREAD

**Issue by squalou** [evilsocket/opensnitch#497]
Hi

**Describe the bug**

Arch AUR package won't build for 1.4.0

**To Reproduce**

On Arch Linux (or derivatives), use for instance `yay` as AUR helper.

1. yay opensnitch
2. wait
3. See error : go compilation error

**Post error logs:** 
```
go: finding module for package github.com/evilsocket/opensnitch/daemon/ui/protocol
go: downloading github.com/evilsocket/opensnitch v1.4.0
conman/connection.go:17:2: module github.com/evilsocket/opensnitch@latest found (v1.4.0), but does not contain package github.com/evilsocket/opensnitch/daemon/ui/protocol
make: *** [Makefile:15: opensnitchd] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
error making: opensnitch

```

**Screenshots**

**OS (please complete the following information):**
 - OS: ArchLinux
 - Window Manager: XFCE
 - Kernel version: 5.13.13-arch1-1
 - Version N/A

**Additional context**

I looks like #494

I would say it's not a duplicate since it's another build system. But you may want to group the two issues.
I did not manage to use info there to fix my issue though.

**Comment by gustavo-iniguez-goya** [comment]
can you check if daemon/ui/protocol/ui_pb.go exists?

What's the output of `make protocol` from the root directory?

**Comment by fractal-fumbler** [comment]
@squalou, please define which pkgrel version of version 1.4.0 you are trying to build.

i have successfully built 1.4.0-2 and 1.4.0-3.

**Comment by squalou** [comment]
it was 1.4.0-2

Long story short : seems to work with 1.4.0-3 :-)

thank you !

Note : 
When trying 1.4.0-3 after 1.4.0-2,,
there is a strange error at the beginning : 

```
rm: cannot remove '~/.cache/yay/opensnitch/src/gopath/pkg/mod/google.golang.org/protobuf@v1.23.0/encoding/protojson/encode_test.go': Permission denied
```

same message for all files : they are all with chmod 444

(of course I manually deleted them for a quick fix)

After successful build, `src` is now gone so I suppose this is all fixed in new PKGBUILD?
